main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Classes
    url: /weeks/
    weight: 4
  - name: Ed
    url: https://us.edstem.org/courses/2296/discussion/
    weight: 5
  - name: Gradescope
    url: https://www.gradescope.com/courses/158258
    weight: 6
  - name: Slack
    url: https://gov-51-f20-qd2.slack.com/
    weight: 7
