---
title: "Week 0: Introduction"
linktitle: "0: Introduction"
summary: "What to do in the first week of of Gov 51"
date: 2020-08-07
menu:
  weeks:
    parent: Weeks
    weight: 1
type: docs
---



## Reading

- Make sure to read the [syllabus](/syllabus/).
- Sections 1.1-1.4 of Quantitative Social Science. 
- Read Chapter 2 of [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) up to section 2.6 to get a feel for R Markdown files that we'll use for problem sets. If you have never used markdown before, section 2.5 will be especially useful.  

## Tutorials

- Before getting started with the course, please complete [the guide on getting your software setup][ps0] which will guide you through installing the relevant tools for the course. 
- Install the `qsslearnr` package that contains the tutorials, following [these instructions][tut]. 
- Complete "QSS Tutorial 0: Introduction to R" and upload the PDF report you produce at the end of the tutorial to Gradescope (see link at the top of this page). 

## Problem Set 0

- We now have a [Problem Set 0][ps0-turnout] available to complete. It will not count toward your overall grade, but will give you practice at using R and RMarkdown and all of the tools we will use to complete assignments in this course. 
- Please read the [Problem Set and Exam Instructions][ps-instructions] on how to access the problem sets and how to submit them to Gradescope. 

[ps0]: /assignments/00-r-intro/
[tut]: /assignments/tutorials/
[ps0-turnout]: /assignments/ps0-turnout/
[ps-instructions]: /assignments/problem-sets/
