---
title: "Week 1: Randomized Experiments"
linktitle: "1: Randomized Experiments"
summary: "Materials for week 1 of Gov 51"
date: 2020-08-07
menu:
  weeks:
    parent: Weeks
    weight: 1
type: docs
---

## Reading

- Sections 2.1-2.4 of Quantitative Social Science.

## Tutorials

- Complete "QSS Tutorial 1: Causality I" and upload the PDF report you produce at the end of the tutorial to Gradescope (see link at the top of this page) by Monday, September 7th 11:59pm ET. 
- If you have any issues opening the tutorial, please see the instructions on [how to install the tutorials](/assignments/tutorials/).

## Problem Sets

- [Problem Set 1](/assignments/ps1-trains/) is due on Wednesday 9/16 at 11:59pm. 


## Lecture Video 1: Introduction to Causality

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/gyRZSzCtU_o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- [Slides](/slides/videos/01-potential-outcomes.pdf)

## Lecture Video 2: Randomized Experiments

<iframe width="560" height="315" src="https://www.youtube.com/embed/cBYUuD2aVkA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [Slides](/slides/videos/02-rand-exp.pdf)


## Live Meeting 

- Data: [`transphobia.csv`](/data/transphobia.csv)
- Completed Rmd file with all prompts: [`week-01-notes.Rmd`](/weeks/week-01-notes.Rmd)
- [Zoom Recording](https://canvas.harvard.edu/courses/74805/external_tools/53531) (Go to "Cloud Recordings" Tab)

## R Coding Demonstration

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/-e1iauR8d1s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Data: [`transphobia.csv`](/data/transphobia.csv)
- Completed Rmd file with all prompts: [`week-01-notes.Rmd`](/weeks/week-01-notes.Rmd)
