---
title: "Week 7: Interactions and Nonlinearities in Regression"
linktitle: "7: Interactions and Nonlinearities"
summary: "Materials for week 7 of Gov 51"
date: 2020-10-19
menu:
  weeks:
    parent: Weeks
    weight: 7
type: docs
---

## Reading

- Sections 4.3 of Quantitative Social Science.

## Tutorials

- Complete "QSS Tutorial 6: Prediction II" and upload the PDF report you produce at the end of the tutorial to Gradescope (see link at the top of this page) by Monday, October 19th 11:59pm ET. 
- If you have any issues opening the tutorial, please see the instructions on [how to install the tutorials](/assignments/tutorials/).

## Exam 1

- [Exam 1](/assignments/exam-01/) is due at 11:59pm ET on Wednesday, October 21, 2020. 

## Lecture Video 16: Varying Effects by Groups

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/0M4iiM5aaiE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [Slides](/slides/videos/16-interactions-binary.pdf)

## Lecture Video 17: Interactions with Continuous Variables


<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Re2t0DRbR_o" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- [Slides](/slides/videos/17-interactions-continuous.pdf)

## Lecture Video 18: Nonlinear Relationships 

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/9-D9TOEvV9g" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- [Slides](/slides/videos/18-nonlinearities.pdf)


## Live Meeting

- Data: [`transphobia_all.csv`](/data/transphobia_all.csv)
- Slides with base R solutions: [Slides](/slides/week-07-slides.pdf)
- Slides with tidyverse solutions: [Slides](/slides/week-07-tidy-slides.pdf)
- [Zoom Recording](https://canvas.harvard.edu/courses/74805/external_tools/53531) (Go to "Cloud Recordings" Tab)
- [Video of Prof Blackwell's base R solutions](https://youtu.be/Jo_wsN7JRYE): Note that in the Zoom recording for the Tuesday base R meeting, I forgot to begin recording again for Question 3, so definitely look at this link for how to complete that question. 
