---
title: "Week 10: Inference and Estimation"
linktitle: "10: Inference and Estimation"
summary: "Materials for week 10 of Gov 51"
date: 2020-11-09
menu:
  weeks:
    parent: Weeks
    weight: 10
type: docs
---

## Reading

- Sections 7.1 of Quantitative Social Science.

## Tutorials

- Complete "QSS Tutorial 9: Uncertainty I" and upload the PDF report you produce at the end of the tutorial to Gradescope (see link at the top of this page) by Monday, November 9th 11:59pm ET. 
- If you have any issues opening the tutorial, please see the instructions on [how to install the tutorials](/assignments/tutorials/).


## Lecture Video 26: Estimators

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/4v3lBuw3M8c" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [Slides](/slides/videos/26-estimators.pdf)

## Lecture Video 27: Confidence Intervals

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/qVRg1bfDx4A" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


- [Slides](/slides/videos/27-conf-int.pdf)

## Lecture Video 28: Inference for Experiments

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/CcbiQGje0vg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- [Slides](/slides/videos/28-experiment-inference.pdf)


## Live Meeting

- Data: [`minwage.csv`](/data/minwage.csv)
- Tuesday slides with solutions: [Slides](/slides/week-10-slides.pdf)
- Thursday slides with tidy solutions: [Slides](/slides/week-10-tidy-slides.pdf)
- [Zoom Recording](https://canvas.harvard.edu/courses/74805/external_tools/53531) (Go to "Cloud Recordings" Tab)
